### ISSUE TITLE
Update NPM?

### ISSUE THREAD

**Issue by skevy** [omniscientjs/omniscient-hot-reload-loader#7]
Hey there - 

Noticed that you pulled in my PR's, but didn't update NPM. Anyway that could happen?

Thanks!
-Adam

**Comment by skevy** [comment]
Nvm on this. react-hot-loader works now!

**Comment by mikaelbr** [comment]
Hi and sorry for the late response! Yeah, AFAIK, with the latest changes to react-hot-loader, you shouldn't need separate omniscient hot-reloader (see also #6). We are probably going to deprecate this package. What do you think @torgeir ?

**Comment by torgeir** [comment]
Yep, we should just verify that it works like #6 suggests, and rewrite the omniscient-hot-reload-loader example
